###

POST http://localhost:9000/api/users HTTP/1.1
content-type: application/json

{
    "name": "otro usuario",
    "age": "43",
    "email": "prueba@api3.com"
}

###
GET  http://localhost:9000/api/users

###
GET  http://localhost:9000/api/users/639a01b5a3edcf7ad923c61f
